### ISSUE TITLE
connected message fired too often, incorrectly?

### ISSUE THREAD

**Issue by sujal** [ttezel/twit#129]
https://github.com/ttezel/twit/blob/master/lib/oarequest.js#L164

Doesn't that line get called any time a chunk of data comes in on the stream (i.e. possibly multiple times a tweet)?

It was part of this commit: https://github.com/ttezel/twit/commit/76395c015109def826e505d10bb65b28b63d77f7

Not sure what the intent is - I thought that message was supposed to let us know the socket connected and to be able to inspect the response...?

Sujal

**Comment by MeanwhileMedia** [comment]
@matomesc, was this ever fixed? I'm still seeing the connected event fire constantly. Thanks.

**Comment by talha-asad** [comment]
Yes me too.

**Comment by Sparragus** [comment]
This just happened to me. Actually, sometimes it takes a while to 're-connect' again. And I have no way of knowing when it will automatically reconnect. Furthermore, those reconnects are sometimes fake. Even though the connect event is fired, it does not connect properly since if I do a tweet that I know for sure will be captured by the stream, the 'tweet' event does not occur.

I'd be happy to help fix this bug if someone can point me in the right direction.

![image](https://cloud.githubusercontent.com/assets/80982/9943764/0eb0a978-5d49-11e5-9d41-42970b82dfb4.png)

**Comment by ttezel** [comment]
This has been fixed! Run `npm update twit` to get the latest version. Thanks!
