### ISSUE TITLE
How resource intense is twit?

### ISSUE THREAD

**Issue by peterwarbo** [ttezel/twit#185]
I'm wondering how resource intense it is. Can I initialize let says a 1000 twit clients (think a multi-user scenario) and have them dormant, and then once in a while do a .get with one of those clients?

Or is it better that I just keep token and tokenSecret available and initialize the twit client when needed?

**Comment by camj256** [comment]
Twitters api is rate limited so you'd have to have a different account for each for that to make sense. Even then I don't see why you wouldn't just store the token info and grab it whenever an account needs something done.

**Comment by ttezel** [comment]
If you are not making requests often, it is probably easier to just instantiate a single Twit instance and use `.setAuth` to set the credentials:
```
var twit = new Twit(initialCredentials);
...
twit.setAuth(newCredentials);
twit.get(...)
```

**Comment by ttezel** [comment]
If you are making many requests concurrently, then I think it is feasible to have a pool of Twit instances that you call `.setAuth()` on with the current user's credentials. However, it should be cheap/low latency to instantiate a new Twit instance when you need it, so rather than having a pool of Twit instances you could also just probably instantiate a new instance each time you need it.

**Comment by camj256** [comment]
No point with one core tho

**Comment by ttezel** [comment]
@camj256 no point in doing what?

**Comment by ttezel** [comment]
Closing this
