### ISSUE TITLE
Changing tracking params without stopping socket

### ISSUE THREAD

**Issue by laukamp** [ttezel/twit#192]
Is it possible to update track parameter on the fly without stoping the socket?

var stream = T.stream('statuses/filter', { track: trendsToTrack });
stream.stop();
stream = T.stream('statuses/filter', { track: OtherTrendsToTrack });

Thank you!

**Comment by anthonywebb** [comment]
I would like to know this as well, however, I tend to think this isnt possible

**Comment by anthonywebb** [comment]
What would be perfect for me is a way to do something like:
stream.startTracking('foo');
stream.stopTracking('bar');

This way I could change them on the fly, I can build it, would just like some confirmation on if it is even possible given the way that twitters streaming api works?

**Comment by ttezel** [comment]
You can't reconnect very often to the Twitter API - you'll get rate limited if you do that. If you're okay with changing the keywords something like once every few minutes, then you can probably run #90 without issue - just run the code there when your keywords change.

If your keywords change a LOT and you want to get EVERYTHING, then your best option is to rotate credentials - create a few Twitter accounts, make credentials for them on the developer website, and use twit.setauth() to rotate credentials. That will help you not get rate limited. But I'd probably recommend the first option since it's less abusive of Twitter :)
