### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by mattdell** [ttezel/twit#193]
I'm trying to build a quick proof of concept with the following code...

```
T.get('users/show', {screen_name: username}, function(err, data, response) {
  console.log(data);
});
```
But on execution it fails rather swiftly with a CORS error.
```
OPTIONS https://api.twitter.com//oauth2/token Request.end @ request.js:143Request.end @ request.js:1363Request.init.end @ request.js:551(anonymous function) @ request.js:577onNextTick @ main.js:64Item.run @ browser.js:62drainQueue @ browser.js:33
(index):1 XMLHttpRequest cannot load https://api.twitter.com//oauth2/token. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 400.
helpers.js:114 Uncaught TypeError: Cannot read property 'token_type' of undefined
```

Any ideas? I'm assuming the library has CORS support as it would be rather limiting to have an API that could only be called from within Twitter.

**Comment by ttezel** [comment]
I don't think you will be able to use the Twitter REST or Streaming APIs at all from most web browsers. The reason why is that they will send that OPTIONS request to Twitter (which I don't think you can block). Since that request fails, the brower won't perform the actual HTTP GET request you wanted to perform. You'll have to make the request from a server or some other enviroment that is not within the browser. You can for example make an HTTP request from your browser to a node.js web server that then uses twit to make use of the Twitter API.

**Comment by juanarbol** [comment]
@ttezel Thanks! I was very close to lose my mind!

**Comment by alperenarc** [comment]
> @ttezel Thanks! I was very close to lose my mind!
@mattdell
Hello. I also faced this problem. How did you solve this problem? Do you remember ? I am very close to lose my mind :)
