### ISSUE TITLE
401 on stream but not on rest requests

### ISSUE THREAD

**Issue by adnida** [ttezel/twit#194]
Hi Tolga,

I haven't managed to authenticate streaming request with my creds. Let me know if this could be a bug or a negligence on my part? Using Twit 2.0.1.

```javascript
var t = new twit({
  consumer_key: config.twitter.consumerKey,
  consumer_secret: config.twitter.consumerSecret,
  app_only_auth: true
});

// this works perfectly fine
t.get('search/tweets', {
  q: 'banana',
  count: 1,
  result_type: 'recent'
}, function (err, data) {
  console.log(data.statuses[0].id);
});

// this returns 401
var stream = t.stream('statuses/filter', {
  track: 'banana'
});

```

stream request returns:
```javascript
{ [Error: Bad Twitter streaming request: 401]
  message: 'Bad Twitter streaming request: 401',
  code: null,
  allErrors: [],
  twitterReply: '<html>\\n<head>\\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\\n<title>Error 401 Unauthorized</title>\n</head>\n<body>\n<h2>HTTP ERROR: 401</h2>\n<p>Problem accessing \'/1.1/statuses/filter.json?track=apple\'. Reason:\n<pre>    Unauthorized</pre>\n</body>\n</html>\n',
  statusCode: 401 }
```

**Comment by rag3rac3r** [comment]
Have you checked that your time is not off?
I had this problem recently, turned out that the time was 600 seconds off for me.

**Comment by adnida** [comment]
@rag3rac3r hi daniel, can you please enlighten me what you meant by time? first time trying this stream api might have missed some points on the docs :) thanks.

**Comment by 1cgonza** [comment]
I believe the problem is that you can't connect to a stream without an access token. See here (https://dev.twitter.com/oauth/application-only) where it says: "And it won’t be able to: ... Connect in Streaming endpoints;" That is probably why your search works fine, but not the stream.

So, "var t" should look something like this after you get your access token and access token secret:
var t = new twit({
  consumer_key: config.twitter.consumerKey,
  consumer_secret: config.twitter.consumerSecret,
  access_token: config.twitter.accessToken,
  access_token_secret: config.twitter.accessTokenSecret
});

**Comment by srigi** [comment]
Time was an issue for me. Thank for the hint. My server clock was off by couple of minutes and Twitter was rejecting my stream request by 401 code. Installing NTP daemon solved the problem for good.

**Comment by ttezel** [comment]
Hi @adnida feel free to reopen if resetting your clock did not fix the issue. Thanks!

**Comment by jmercadodev** [comment]
I fixed it by simply rebooting my Linux server.
