### ISSUE TITLE
Possibility to add hashtag to open stream

### ISSUE THREAD

**Issue by peerbolte** [ttezel/twit#218]
What would be the cleanest way to add / remove a hashtag to a running stream without losing posts?

**Comment by roppa** [comment]
It looks like params.track is exposed in the stream. Possibly changing that as I can't see any getter/setters?

**Comment by peerbolte** [comment]
I have an aggregation application where the hashtags that need to be tracked frequently change. Any idea how to implement such functionality using this module? I'm now using two streams that switch: when a hashtag is added or removed I stop the current stream and update the other stream with the new array of hashtags. I'm not too keen on this solution as it feels a bit hacky and there seems to be a delay when starting a new stream. 

Regarding params.track: when I log the stream I get the following output (no params.track)

```javascript
EventEmitter {
  reqOpts: 
   { headers: {},
     url: 'https://stream.twitter.com/1.1/statuses/filter.json?track=%23ronaldo',
     oauth: 
      { consumer_key: 'xxx',
        consumer_secret: 'xxx',
        token: 'xxx',
        token_secret: 'xxx' } },
  twitOptions: {},
  domain: null,
  _events: {},
  _eventsCount: 0,
  _maxListeners: undefined }
```

**Comment by dsalcedo** [comment]
you need stop and reconnect :/

**Comment by ttezel** [comment]
You can't reconnect very often to the Twitter API - you'll get rate limited if you do that. If you're okay with changing the keywords something like once every few minutes, then you can probably run #90 without issue - just run the code there when your keywords change.

If your keywords change a LOT and you want to get EVERYTHING, then your best option is to rotate credentials - create a few Twitter accounts, make credentials for them on the developer website, and use twit.setauth() to rotate credentials. That will help you not get rate limited. But I'd probably recommend the first option since it's less abusive of Twitter :)
