### ISSUE TITLE
Bad Twitter streaming request: 401

### ISSUE THREAD

**Issue by stevefister** [ttezel/twit#222]
Any ideas on why I'm getting this? My server time is in sync, so it's not that.....

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Bad Twitter streaming request: 401
    at Object.exports.makeTwitError (/mnt/sda1/node-omega-gpio-master/node_modules/twit/lib/helpers.js:74:13)
    at IncomingMessage.<anonymous> (/mnt/sda1/node-omega-gpio-master/node_modules/twit/lib/streaming-api-connection.js:92:29)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:895:16
    at process._tickCallback (node.js:415:13)

**Comment by stevefister** [comment]
Bump

**Comment by ctricot** [comment]
Hello

I have the same problem :
{ [Error: Bad Twitter streaming request: 401]
  message: 'Bad Twitter streaming request: 401',
  code: null,
  allErrors: [],
  twitterReply: '<html>\\n<head>\\n<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\\n<title>Error 401 Unauthorized</title>\n</head>\n<body>\n<h2>HTTP ERROR: 401</h2>\n<p>Problem accessing \'/1.1/statuses/filter.json?track=medtech\'. Reason:\n<pre>    Unauthorized</pre>\n</body>\n</html>\n',
  statusCode: 401 }

**Comment by stevefister** [comment]
What system/architecture are you running this on?



Thanks!

Steve Fister

**Comment by laurensdv** [comment]
Same issue here on Ubuntu 15.10

**Comment by the-bobo** [comment]
i'm getting this issue too, running on Ubuntu Precise (headless) inside a tmux session.

**Comment by ttezel** [comment]
Hi @the-bobo @stevefister this is now fixed; Twit now automatically adjusts its time offset based on the last HTTP response it received from Twitter. So if a given HTTP request fails, retrying it will work because Twit adjusts its timestamp from the HTTP response it last received. You now have 2 options: either calling T.get(), seeing if you got an error and retrying if you got an error, or you can use the `retry` option in Twit to have it retry the request once automatically for you if it fails:
```
T.get('...', { some: 'thing', twit_options: { retry: true } }, function (err, data, resp) { 
 //...
})
```

Run `npm update twit` to get the latest version. Thanks!
