### ISSUE TITLE
401 on Stream. Wut?

### ISSUE THREAD

**Issue by ichy-wayland** [ttezel/twit#229]
**The Error:**

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Bad Twitter streaming request: 401
    at Object.exports.makeTwitError (/home/dimitri/node-projects/twit_test/node_modules/twit/lib/helpers.js:74:13)
    at IncomingMessage.<anonymous> (/home/dimitri/node-projects/twit_test/node_modules/twit/lib/streaming-api-connection.js:92:29)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)
**The Code:**
var Twit = require('twit')
var Twitter = require('twitter')
var sleep = require('sleep')

var t = new Twit ( {
  consumer_key: '',
  consumer_secret: '',
  app_only_auth: true
})

var stream = t.stream('statuses/sample')

stream.on('tweet', function (tweet) {
  console.log(tweet)
})

**Notes:**
Yes, i tryed with the full authentication (Acess Token, Acess Token Secret)

**Comment by amenadiel** [comment]
time sync perhaps?

**Comment by ichy-wayland** [comment]
Already tryed. Used ntp pool and ubuntu servers, but nothing.
(I dont use ubuntu.)

**Comment by ichy-wayland** [comment]
(It may be the Twitter Time. I dont know what timezone is it synced with.)

**Comment by ttezel** [comment]
Hi @ichy-wayland @amenadiel Twit now automatically adjusts its time offset based on the last HTTP response it received from Twitter. So if a given HTTP request fails, retrying it will work because Twit adjusts its timestamp from the HTTP response it last received. You now have 2 options: either calling T.get(), seeing if you got an error and retrying if you got an error, or you can use the `retry` option in Twit to have it retry the request once automatically for you if it fails:
```
T.get('...', { some: 'thing', twit_options: { retry: true } }, function (err, data, resp) { 
 //...
})
```
