### ISSUE TITLE
How to store streaming API tweets in a variable(array)?

### ISSUE THREAD

**Issue by chubaka** [ttezel/twit#267]
Hi, I have connected OK to the straming API and getting each new tweet, however I am trying to push each new tweet to a variable so that I can later loop though it. I need to be able to add a new 'li' each time a new tweet comes in. Right now it simply replaces the old 'li'
Here is my code.
var arr;
var ids=T.get('friends/ids',  function (err, data, response) {
  var idlist = data.ids;
  var stream = T.stream('statuses/filter', { follow: idlist }, { track: keyword })
    stream.on('tweet', function (tweet) {
      text = tweet.text;
      sn = tweet.user.screen_name;
      imgurl = tweet.user.profile_image_url;
      name = tweet.user.name;
      time = tweet.user.created_at;
      tweet = {text:text, sn:sn, name:name, time:time, imgurl:imgurl };
 var arr=[];
 arr.push(tweet);
 console.log(arr);
})

When I cosole.log(arr); it gives me the new tweet only, it does not add to it. Can you help?

**Comment by super-ienien** [comment]
Hi,

I think this is not the right place to ask this kind of help... This is not an issue related to the twit library itself. You should go on a forum like stackoverflow.

Anyway, your code is not well structured, you should improve your javascript skills and knowledge. The problem here (and it's not the only one) is that you are creating a new Array each time you receive a tweet. So you are adding a tweet to an empty array each time. That is why you are printing an array with only one tweet in the console. You just need to remove this line : `var arr=[];` and to append `=[]`; to your first line

**Comment by chubaka** [comment]
Thanks for your answer, will check with stackoverflow next time.
