### ISSUE TITLE
How search by Place and  Date?

### ISSUE THREAD

**Issue by 710rent** [ttezel/twit#360]
I want to search by Place and Date, I've tried it that way:
T.get('search/tweets', { q : 'place:fe9920bab873592f since:2017-05-28', lang : 'es'}, function (err, data, response) { ... });

but the results is only of the last hour.

**Comment by klaveren** [comment]
See the documentation at: https://dev.twitter.com/rest/reference/get/search/tweets

Your parameter is wrong. Try {q: 'place: fe9920bab873592f, until: 2017-05-28', lang: 'es'}

You need to comma each parameter.

Change the Since for Until property,
UNTIL: Returns tweets created before the given date. The date must be formatted as YYYY-MM-DD. Keep in mind that the search index has a limit of 7 days. In other words, no tweet will be found for a date longer than a week.

Another thing is the limit of returns, which should be observed:
Requests / 15-min window (user auth) 180
Requests / 15-min window (app auth) 450

If it exceeds you will need to paginate your query.

**Comment by ttezel** [comment]
As @klaveren mentioned above, please read the docs at https://dev.twitter.com/.
