### ISSUE TITLE
answering to tweets doesn't work properly

### ISSUE THREAD

**Issue by ChandlerMBing** [ttezel/twit#437]
I've made it so that whenever someone tweets at the bot account it answers with a changed @ tag and shuffled words with lodash. Anyway, every time it answers, the bot just keeps on posting until it throws an error for repeated tweet, same thing happens when trying to re-tweet, does it once and then throws an error for trying to re-tweet it again. Code is pretty straight forward so not sure why this happens:

```js
const stream = T.stream("user");
function reply(res) {
  const message = shuffle(
    res.text.replace(/botAccount/, res.user.screen_name).split(" ")
  ).join(" ");

    T.post("statuses/update", {status: message}, tweeted);
//OR for retweets
  const id = res.id_str;
  T.post("statuses/retweet/:id", { id }, tweeted);
}
stream.on("tweet", reply);
```

**Comment by ttezel** [comment]
@ChandlerMBing can you post a more complete code sample? I think the error lies in the structure of the code outside of what's posted here

**Comment by ttezel** [comment]
Doesn't seem like this is an issue with the `twit` module - if you're getting an error for trying to post a tweet containing content similar to one you recently posted, that's happening because Twitter's API is blocking you from doing that (to prevent spam). Feel free to reopen if you find that Twit is causing this issue. Also if you provide a code sample I can help debug

**Comment by ChandlerMBing** [comment]
OK, so I think the best way to explain is with some screen shots, because that's all the code there is, not counting the `const T  = new Twit({...})`, but that's definitely ok because I'm able to tweet from node but when it comes to replying or retweeting it goes haywire.

Running the callback with a console.log.
<img width="928" alt="reply_console" src="https://user-images.githubusercontent.com/23351348/40910682-583e2064-681f-11e8-8353-19b20b256833.png">
runs once
<img width="562" alt="reply_terminal" src="https://user-images.githubusercontent.com/23351348/40910683-588def18-681f-11e8-9bd3-f7c66c9491d7.png">
running the callback with T.post
<img width="903" alt="reply_post" src="https://user-images.githubusercontent.com/23351348/40910685-58cce6a0-681f-11e8-837a-933416f38c57.png">
runs 4 times and throws an error.
<img width="1392" alt="reply_post_terminal" src="https://user-images.githubusercontent.com/23351348/40910686-590b05a2-681f-11e8-97c7-84c59ef7b0de.png">

**Comment by ttezel** [comment]
Hi @ChandlerMBing I replied in the other issue you opened, but to clarify here, this is NOT an issue with `twit`. The Twitter API is blocking your tweets because you're posting similar content over and over again. There is nothing `twit` or any other twitter API client can do to get around this. You need to ensure that you're not posting very similar tweets over and over again.
