### ISSUE TITLE
Use another Account

### ISSUE THREAD

**Issue by OfficialCRUGG** [ttezel/twit#516]
How do I use another account with Twit?
I have a main account where I have my app on, but I want to have my bot running on a different account. How would I achieve this?

**Comment by friaca** [comment]
I don't think you can besides getting a new API key for the other account aswell.

**Comment by OfficialCRUGG** [comment]
And how do I get this API Key?

**Comment by pantchox** [comment]
You go to twitter developer portal in the apps section - https://developer.twitter.com/en/apps/ and click "create  an app" button.

then you will need to fill in submission, if its your first app it will be pending for sometime (For me took few hours) after that you can create more apps.

each app has tokens data which you feed in with twit but since they are apps each is individual though also they are different with rate limit comparing to your twitter user tokens.

good luck.

**Comment by OfficialCRUGG** [comment]
I know how to create apps, but I want to know how to do stuff as another user. I can't just go through the multiple day long developer application process and then create the same app on every account. And how are users of the server supossed to do that?

**Comment by pantchox** [comment]
If you want to do actions on behalf of a user, you are suppose to create an app which the property "Sign in with Twitter" is enabled. so the user you wish to do actions in behalf of him such as a tweet or whatever can sign in to your app and give your app permission, is this what you are trying to do? even if your other twitter user is your own different account (private/biz)

**Comment by OfficialCRUGG** [comment]
Exactly. But if I enable "Sign in with Twitter", what exactly do I need to do then? How do I make an authorization link and how to I post on the account then?
