### ISSUE TITLE
Working with twit on frontend

### ISSUE THREAD

**Issue by xgrommx** [ttezel/twit#67]
Could you please provide an example how I can use 'twit' on my fronted like a socket.io-client?

**Comment by iamstarkov** [comment]
browserify?

**Comment by angelxmoreno** [comment]
Anyone in the community experienced with browserify should really give it a shot and report their findings. It would really help out the twit community.

**Comment by ttezel** [comment]
I don't think this will work in a browser because of the preflight OPTIONS request that it will send to Twitter (which will fail). Then the browser will not perform the original GET or POST request that you wanted to perform. So I think you'll have to use Twit from another environment other than a browser (eg. a node.js server).

**Comment by Tiendq** [comment]
webpack can't resolve `fs` module, I didn't know that and was trying to use `twit` in an example :)
