### ISSUE TITLE
Feature request: stream event for 401 Timestamp errors.

### ISSUE THREAD

**Issue by MeanwhileMedia** [ttezel/twit#85]
So I was going crazy for a couple days trying to figure out why my open statuses/filter stream was not throwing any events. There was no disconnect event, or error thrown, it just wasn't working. Turns out it was because my server time was out of sync with Twitter's time. It was an easy fix, but it'd be cool if twit could let you know. See here for more:

https://dev.twitter.com/discussions/686

Maybe a feature could be added to twit to automatically adjust request timestamps based on the local time offset? That would be much nicer than having to change the server's timezone just for the twitter api.

Thanks,
Joe

**Comment by talha-asad** [comment]
+1

**Comment by ttezel** [comment]
@talha-asad @MeanwhileMedia Twit now automatically adjusts its time offset based on the last HTTP response it received from Twitter. So if a given HTTP request fails, retrying it will work because Twit adjusts its timestamp from the HTTP response it last received. You now have 2 options: either calling T.get(), seeing if you got an error and retrying if you got an error, or you can use the `retry` option in Twit to have it retry the request once automatically for you if it fails:
```
T.get('...', { some: 'thing', twit_options: { retry: true } }, function (err, data, resp) { 
 //...
})
```

Run `npm update twit` to get the latest version. Thanks!
